"""Add detailed response fields to SurveyResponse

Revision ID: 0726b626ddf5
Revises: 8edb35782350
Create Date: 2025-06-15 23:39:54.174578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0726b626ddf5'
down_revision = '8edb35782350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('form_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('utm_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ip_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('click_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('browser', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('device_type', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_response', schema=None) as batch_op:
        batch_op.drop_column('device_type')
        batch_op.drop_column('browser')
        batch_op.drop_column('click_data')
        batch_op.drop_column('ip_data')
        batch_op.drop_column('utm_data')
        batch_op.drop_column('form_status')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
