"""Add external form fields to Survey model

Revision ID: 279f9e07b557
Revises: 9ca6c4e1e8d7
Create Date: 2025-06-18 17:21:58.092773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279f9e07b557'
down_revision = '9ca6c4e1e8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_external', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('external_url', sa.String(length=500), nullable=True))
        batch_op.drop_column('is_external_form')
        batch_op.drop_column('external_form_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_form_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_external_form', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('external_url')
        batch_op.drop_column('is_external')

    # ### end Alembic commands ###
