"""Add merged_user_data to Survey

Revision ID: 3d3e2d4285d3
Revises: e7aac5159821
Create Date: 2025-06-08 04:28:55.434125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d3e2d4285d3'
down_revision = 'e7aac5159821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merged_user_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.drop_column('merged_user_data')

    # ### end Alembic commands ###
