"""Add merged_user_data to Survey

Revision ID: 8edb35782350
Revises: 3d3e2d4285d3
Create Date: 2025-06-08 04:34:45.024342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8edb35782350'
down_revision = '3d3e2d4285d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('who_merged', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.drop_column('who_merged')

    # ### end Alembic commands ###
