"""Add geolocation data to SurveyResponse

Revision ID: 9ca6c4e1e8d7
Revises: 0726b626ddf5
Create Date: 2025-06-16 00:39:51.176038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca6c4e1e8d7'
down_revision = '0726b626ddf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geolocation_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_response', schema=None) as batch_op:
        batch_op.drop_column('geolocation_data')

    # ### end Alembic commands ###
