"""Add user_id and company_name to Response

Revision ID: e7aac5159821
Revises: 
Create Date: 2025-06-02 14:55:58.154974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7aac5159821'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_response', schema=None) as batch_op:
        batch_op.alter_column('respondent_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_response', schema=None) as batch_op:
        batch_op.alter_column('respondent_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
